### ISSUE TITLE
[BUG]  "Resource not accessible by integration"

### ISSUE THREAD

**Issue by edgarriba** [tiena2cva/action-emoji#8]
hi, we recently started using your project and sometimes it fails with the following error:
```bash
Load user config from ./.github/emoji.yml
Loaded 674 emoji
Add emoji :books: to title
Traceback (most recent call last):
  File "/emoji.py", line 87, in <module>
    pull.edit(title=f":{emoji}: {pull.title.strip()}")
  File "/usr/local/lib/python3.8/site-packages/github/PullRequest.py", line 588, in edit
    headers, data = self._requester.requestJsonAndCheck(
  File "/usr/local/lib/python3.8/site-packages/github/Requester.py", line 315, in requestJsonAndCheck
    return self.__check(
  File "/usr/local/lib/python3.8/site-packages/github/Requester.py", line 340, in __check
    raise self.__createException(status, responseHeaders, output)
github.GithubException.GithubException: 403 {"message": "Resource not accessible by integration", "documentation_url": "https://docs.github.com/rest/reference/pulls#update-a-pull-request"}
```
URL: https://github.com/kornia/kornia/pull/1393/checks?check_run_id=3914880023

----
Any idea why would that happen ?

**Comment by tiena2cva** [comment]
@edgarriba Thank for your feedback. I will check it tonight.
